image: node:latest

include:
  - template: Security/License-Management.gitlab-ci.yml

stages:
  - test
  - compatibility
  - release

test:
  stage: test
  coverage: /Branches\s+:\s(\d+.\d+%)/
  before_script:
    - npm ci
  script:
    - npm test -- --ci
    - npm run eslint -- --max-warnings 0
    - npm run prettier:check
  artifacts:
    name: ${CI_PROJECT_PATH_SLUG}-${CI_PIPELINE_ID}-jest
    paths:
      - coverage/
    reports:
      junit: build/*.junit.xml

.compat: &compat
  stage: compatibility
  before_script:
    - npm ci
  script:
    - npm test

Node 8.x (LTS):
  <<: *compat
  image: node:8
  before_script:
    - npm install

Node 10.x (LTS):
  <<: *compat
  image: node:10

Node 12.x (current):
  <<: *compat
  image: node:12

Publish to NPM:
  stage: release
  only:
    - tags
  script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > ~/.npmrc
    - export PKG_VERSION=v$(node -p "require('./package.json').version")
    - echo ${CI_COMMIT_TAG}
    - echo ${PKG_VERSION}
    - test ${CI_COMMIT_TAG} = ${PKG_VERSION}
    - npm publish
